### ISSUE TITLE
Si esta cargado correctamente

### ISSUE THREAD

**Issue by rubencalcano** [rcalcano/miPrimerRepo#10]
**Describe el error**
no hay problemas, funciona correctamente.

**Pasos para reproducirlo**
1. Ir a '...'
2. Hacer clic en '...'
3. Ver el error.

**Comportamiento esperado**
Describe qué esperabas que ocurriera.

**Capturas de pantalla**
Si aplica, añade capturas de pantalla para ayudar.

**Entorno**
- Sistema Operativo: [por ejemplo, Windows 10]
- Navegador: [por ejemplo, Chrome 100]
- Versión del proyecto: [por ejemplo, 1.0.0]

**Información adicional**
Añade cualquier otro detalle que consideres relevante.

**Comment by rcalcano** [comment]
Gracias.
